{{- if .Values.ingress.enabled -}}
{{- if .Values.rstudioUsers -}}
{{- $fullName := include "pecan.fullname" . -}}
{{- $name := include "pecan.name" . -}}
{{- $labels := include "pecan.labels" . -}}
{{- range .Values.rstudioUsers -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-{{ .username }}
  labels:
    {{- $labels | nindent 4 }}
  annotations:
  {{- if $.Values.ingress.tls }}
    kubernetes.io/tls-acme: "true"
    traefik.ingress.kubernetes.io/router.tls: "true"
  {{- end }}
  {{- with $.Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if and $.Values.ingress.tls $.Values.ingress.tlsSecret $.Values.ingress.hosts }}
  tls:
    - hosts:
      {{- with $.Values.ingress.hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ $.Values.ingress.tlsSecret }}
{{- end }}
  rules:
{{- if $.Values.ingress.hosts }}
  {{- $username := .username }}
  {{- range $.Values.ingress.hosts }}
    - host: "{{ $username}}.{{ . }}"
      http:
        paths:
          - path: {{ $.Values.ingress.path }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}-{{ $username }}-headless
                port:
                  name: rstudio
  {{- end }}
{{- else }}
    - host: "{{ .username}}.localhost"
      http:
        paths:
          - path: {{ $.Values.ingress.path }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}-{{ .username }}-headless
                port:
                  name: rstudio
{{- end }}
{{- end }}
{{- end }}
{{- end }}
